# Generated by Django 2.1.2 on 2019-03-07 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='c2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.c1')),
                ('c2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.c2')),
            ],
        ),
        migrations.AddField(
            model_name='s',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.t'),
        ),
    ]
